version: 2.1

orbs:
  newman: postman/newman@1.0.0

jobs:          
    testrail-service-demo:
        description: Run Postman collection tests 
        parameters:
          collection:
            type: string
          temp:
            type: string
        executor: newman/postman-newman-docker
        
        steps:
          - checkout 
          - run:
              name: Installing testrail reporting plugin
              command: |
                npm install newman-reporter-testrail --global
          - run:
              name: Installing htmlextra reporting plugin
              command: |
                npm install -g newman-reporter-htmlextra   
          - run:
              name: Echo Environment Variable
              command: echo ${TESTRAIL_APIKEY}
          - run:
              name: Executing the collection
              command: |
                npx newman run Practice.postman_collection.json --env-var "TESTRAIL_TITLE=<< parameters.temp >>" --env-var TESTRAIL_APIKEY=${TESTRAIL_APIKEY} --reporters "cli,htmlextra,testrail"
                
          - store_artifacts: { path: ~/project/newman }
          - store_test_results: { path: /root/project/newman }       
  
workflows:
  qe-guild-api-automation:
    jobs:      
      - testrail-service-demo:
          name: ERS Demo
          collection: 27218141-242b1743-d251-4ab9-a0fd-24102d0622fb
          temp: "Automated Run: $( date '+%F_%H:%M:%S' )"
          context:
            - postman
            - testrail
      